
pool:
  vmImage: 'macOS-10.13'

steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    platform: 'X86'
    clean: true
    maximumCpuCount: true
    restoreNugetPackages: true
    createLogFile: true